services:
  ## DATABASES
  # POSTGRES
  postgresDB:
    image: dragonhack/postgres-db
    container_name: dragonhack-postgresDB
    build:
      context: .
      dockerfile: postgres/docker/Dockerfile
    ports:
      - ${DB_PORT}:${DB_PORT_INTERNAL}
    volumes:
      - ./postgres/Data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_ADMIN_PASSWORD} # admin password
      - POSTGRES_USER=${DB_ADMIN_USERNAME} # admin user
      - PG_UNAME=${DB_USERNAME} # user
      - PG_PASS=${DB_PASSWORD} # password
      - PG_DB=${DB_DATABASE} # database name

    extra_hosts:
      - "host.docker.internal:host-gateway"

  mailing-service:
    image: dragonhack/mailing-service
    container_name: mailing-service
    restart: always
    build:
      context: .
      dockerfile: ./mailing/docker/Dockerfile
    ports:
      - 8000:8000 # gmail server port for authentication
      - 8080:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ad-cdc:
    image: dragonhack/ad-cdc
    container_name: ad-cdc
    restart: always
    build:
      context: .
      dockerfile: ./cdc/advertisements/docker/Dockerfile
    environment:
      - DB_ADMIN_PASSWORD=${DB_ADMIN_PASSWORD} # admin password
      - DB_ADMIN_USERNAME=${DB_ADMIN_USERNAME} # admin user
      - DB_USERNAME=${DB_USERNAME} # user
      - DB_PASSWORD=${DB_PASSWORD} # password
      - DB_DATABASE=${DB_DATABASE} # database name
      - DB_PORT=${DB_PORT}
      - LOCALHOST=${LOCALHOST}
      - TABLES=${AD_TABLES}
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  noti-cdc:
    image: dragonhack/noti-cdc
    container_name: noti-cdc
    restart: always
    build:
      context: .
      dockerfile: ./cdc/notifications/docker/Dockerfile
    environment:
      - DB_ADMIN_PASSWORD=${DB_ADMIN_PASSWORD} # admin password
      - DB_ADMIN_USERNAME=${DB_ADMIN_USERNAME} # admin user
      - DB_USERNAME=${DB_USERNAME} # user
      - DB_PASSWORD=${DB_PASSWORD} # password
      - DB_DATABASE=${DB_DATABASE} # database name
      - DB_PORT=${DB_PORT}
      - LOCALHOST=${LOCALHOST}
      - TABLES=${NOTIFI_TABLES}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  webscraper:
    image: dragonhack/webscraper
    container_name: webscraper
    restart: always
    build:
      context: .
      dockerfile: ./webscraper/docker/Dockerfile
    environment:
      - DB_ADMIN_PASSWORD=${DB_ADMIN_PASSWORD} # admin password
      - DB_ADMIN_USERNAME=${DB_ADMIN_USERNAME} # admin user
      - DB_USERNAME=${DB_USERNAME} # user
      - DB_PASSWORD=${DB_PASSWORD} # password
      - DB_DATABASE=${DB_DATABASE} # database name
      - DB_PORT=${DB_PORT}
      - LOCALHOST=${LOCALHOST}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  website:
    image: dragonhack/website
    container_name: website
    restart: always
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: ./website/docker/Dockerfile
    environment:
      - DB_ADMIN_PASSWORD=${DB_ADMIN_PASSWORD} # admin password
      - DB_ADMIN_USERNAME=${DB_ADMIN_USERNAME} # admin user
      - DB_USERNAME=${DB_USERNAME} # user
      - DB_PASSWORD=${DB_PASSWORD} # password
      - DB_DATABASE=${DB_DATABASE} # database name
      - DB_PORT=${DB_PORT}
      - LOCALHOST=${LOCALHOST}
    extra_hosts:
      - "host.docker.internal:host-gateway"