#!/bin/sh

set -e

# check if this is the first run of the database
if [ ! -f "/var/lib/postgresql/data/PG_VERSION" ]; then
    echo "initial run, terminating after 120 seconds"
    # run the service without the configuration file to initialize the user
    # and tables
    exec docker-entrypoint.sh "postgres" &
    pg_pid=$!

    sleep 120
    echo "terminating database"
    kill $pg_pid
    wait $pg_pid
fi

# the database is already initialized
echo "starting service with provided configuration"
exec docker-entrypoint.sh "$@" &
pg_pid=$!

# initialize the database
echo "database PID: $pg_pid"
echo "waiting 60 seconds for the database to initialize"
sleep 60

wait $pg_pid